### ISSUE TITLE
Moxie proxy support is incomplete

### ISSUE THREAD

**Issue by fbacchella** [gitblit/moxie#8]
When you define a proxy, you do it with :
   proxies:
   - {
       id: 'myproxy'
       active: true
       protocol: 'http'
       host: 'proxy.somewhere.com'
       port: 8080
       username: 'proxyuser'
       password: 'somepassword'
     }

My proxy is at http://somehost:8081/nexus/content/groups/public. Where can I define the path ?

**Comment by gitblit** [comment]
I hadn't considered paths.

I modeled proxy support after Maven.  How would you define the path in Maven's proxy settings?  AFAICT you can't. https://maven.apache.org/ref/3.3.3/maven-settings/settings.html

**Comment by fbacchella** [comment]
Like that :

    <settings>
        <mirrors>
            <mirror>
                <id>nexus</id>
                <mirrorOf>*</mirrorOf>
                <url>http://somehost:8081/nexus/content/groups/public</url>
            </mirror>
        </mirrors>
    </settings>

**Comment by fbacchella** [comment]
I think we talk about to kind of things. There is the pure http proxies, to allow internet access. That's not the same kind of thing than a mirror, like nexus provides and provide  consolidated view of different repository and does caching too.

**Comment by gitblit** [comment]
Right.  The settings you cited are for configuring http connection proxying.

Are you asking me about configuring [MoxieProxy](http://moxie.gitblit.com/proxy.html)?  (I never did document that.) Or are you asking about the connection proxying?

**Comment by fbacchella** [comment]
I would like to use nexus (already installed) instead of MoxieProxy, but that's the idea yes, a little documentation would be helpful.

**Comment by gitblit** [comment]
The Moxie ant components don't support a *mirror* concept.  What you could do is define a repository in `build.moxie` and declare it to be used first.

```
registeredRepositories:
- { id:'nexus', url:'http://somehost:8081/nexus/content/groups/public' }

repositories: 'nexus', 'central'
```

http://moxie.gitblit.com/moxiedescriptor.html#H11
http://moxie.gitblit.com/moxiedescriptor.html#H13

**Comment by fbacchella** [comment]
Ok, it works. I would have preferred something in the general settings but it does the job.

**Comment by gitblit** [comment]
Ok, I think can do that too.

Move the above snippet to `~/.moxie/settings.moxie`.

You also might be interested in this setting: http://moxie.gitblit.com/settings.html#H9
